name: Offload Scrape Hourly

on:
  schedule:
    - cron: '0 * * * *'   # run at top of every hour (UTC)
  workflow_dispatch:       # allow manual run

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    # Avoid overlapping hourly runs if one is slow
    concurrency:
      group: offload-scrape
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright Chromium (with system deps)
        run: npx playwright install --with-deps chromium

      - name: Run scraper
        env:
          OKTA_EMAIL: ${{ secrets.OKTA_EMAIL }}
          OKTA_PASSWORD: ${{ secrets.OKTA_PASSWORD }}
          OKTA_START_URL: ${{ secrets.OKTA_START_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          # DEBUG_SCRAPE: "1"   # uncomment for verbose local-like logs
        run: npm run scrape:once

      # Optional: keep latest download for debugging
      - name: Upload downloads artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: downloads
          path: downloads/
          if-no-files-found: ignore
          retention-days: 7

